export let questions = [
    {
        id: 1,
        question: "What is the capital of Japan?",
        choices: ["Tokyo", "Seoul", "Beijing", "Bangkok"],
        correctAnswer: "Tokyo",
    },
    {
        id: 2,
        question: "Which planet is known as the Red Planet?",
        choices: ["Mars", "Venus", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
    },
    {
        id: 3,
        question: "Who wrote 'Romeo and Juliet'?",
        choices: ["William Shakespeare", "Jane Austen", "Charles Dickens", "Leo Tolstoy"],
        correctAnswer: "William Shakespeare",
    },
    {
        id: 4,
        question: "What is the largest mammal in the world?",
        choices: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
        correctAnswer: "Blue Whale",
    },
    {
        id: 5,
        question: "In which year did the Titanic sink?",
        choices: ["1912", "1905", "1920", "1931"],
        correctAnswer: "1912",
    },
    {
        id: 6,
        question: "What is the currency of Brazil?",
        choices: ["Peso", "Rupiah", "Real", "Ringgit"],
        correctAnswer: "Real",
    },
    {
        id: 7,
        question: "Which country is known as the Land of the Rising Sun?",
        choices: ["China", "Japan", "South Korea", "Vietnam"],
        correctAnswer: "Japan",
    },
    {
        id: 8,
        question: "What is the capital of Australia?",
        choices: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
        correctAnswer: "Canberra",
    },
    {
        id: 9,
        question: "Who painted the Mona Lisa?",
        choices: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"],
        correctAnswer: "Leonardo da Vinci",
    },
    {
        id: 10,
        question: "Which gas is most abundant in the Earth's atmosphere?",
        choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"],
        correctAnswer: "Nitrogen",
    },
    {
        id: 11,
        question: "In which year did World War II end?",
        choices: ["1943", "1945", "1947", "1950"],
        correctAnswer: "1945",
    },
    {
        id: 12,
        question: "What is the smallest prime number?",
        choices: ["0", "1", "2", "3"],
        correctAnswer: "2",
    },
    {
        id: 13,
        question: "Which ocean is the largest?",
        choices: ["Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Pacific Ocean"],
        correctAnswer: "Pacific Ocean",
    },
    {
        id: 14,
        question: "Who developed the theory of relativity?",
        choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Stephen Hawking"],
        correctAnswer: "Albert Einstein",
    },
    {
        id: 15,
        question: "What is the capital of South Africa?",
        choices: ["Johannesburg", "Durban", "Pretoria", "Cape Town"],
        correctAnswer: "Pretoria",
    },
    {
        id: 16,
        question: "Which is the largest desert in the world?",
        choices: ["Sahara Desert", "Arctic Desert", "Gobi Desert", "Antarctic Desert"],
        correctAnswer: "Antarctic Desert",
    },
    {
        id: 17,
        question: "Which famous scientist developed the theory of general relativity?",
        choices: ["Isaac Newton", "Albert Einstein", "Stephen Hawking", "Niels Bohr"],
        correctAnswer: "Albert Einstein",
    },
    {
        id: 18,
        question: "What is the largest ocean on Earth?",
        choices: ["Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Pacific Ocean"],
        correctAnswer: "Pacific Ocean",
    },
    {
        id: 19,
        question: "In which year did the United States declare its independence?",
        choices: ["1774", "1776", "1789", "1799"],
        correctAnswer: "1776",
    },
    {
        id: 20,
        question: "Who wrote 'Pride and Prejudice'?",
        choices: ["Jane Austen", "Charles Dickens", "Charlotte Brontë", "Leo Tolstoy"],
        correctAnswer: "Jane Austen",
    },
    {
        id: 21,
        question: "What is the currency of Brazil?",
        choices: ["Peso", "Rupiah", "Real", "Ringgit"],
        correctAnswer: "Real",
    },
    {
        id: 22,
        question: "Who discovered penicillin?",
        choices: ["Marie Curie", "Alexander Fleming", "Louis Pasteur", "Joseph Lister"],
        correctAnswer: "Alexander Fleming",
    },
    {
        id: 23,
        question: "What is the capital of Canada?",
        choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
        correctAnswer: "Ottawa",
    },
    {
        id: 24,
        question: "Who is the author of 'To Kill a Mockingbird'?",
        choices: ["J.K. Rowling", "Harper Lee", "George Orwell", "Mark Twain"],
        correctAnswer: "Harper Lee",
    },
    {
        id: 25,
        question: "Which element has the chemical symbol 'O'?",
        choices: ["Oxygen", "Gold", "Osmium", "Iron"],
        correctAnswer: "Oxygen",
    },
    {
        id: 26,
        question: "What is the currency of Japan?",
        choices: ["Yuan", "Yen", "Rupee", "Won"],
        correctAnswer: "Yen",
    },
    {
        id: 27,
        question: "Who painted 'The Starry Night'?",
        choices: ["Vincent van Gogh", "Pablo Picasso", "Leonardo da Vinci", "Claude Monet"],
        correctAnswer: "Vincent van Gogh",
    },
    {
        id: 28,
        question: "Which is the largest ocean on Earth?",
        choices: ["Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Pacific Ocean"],
        correctAnswer: "Pacific Ocean",
    },
    {
        id: 29,
        question: "In which year did the Berlin Wall fall?",
        choices: ["1985", "1989", "1991", "1995"],
        correctAnswer: "1989",
    },
    {
        id: 30,
        question: "What is the capital of South Korea?",
        choices: ["Seoul", "Busan", "Incheon", "Daegu"],
        correctAnswer: "Seoul",
    },
    {
        id: 31,
        question: "Who wrote '1984'?",
        choices: ["George Orwell", "Aldous Huxley", "Ray Bradbury", "Arthur C. Clarke"],
        correctAnswer: "George Orwell",
    },
    {
        id: 32,
        question: "What is the largest desert in Asia?",
        choices: ["Gobi Desert", "Thar Desert", "Arabian Desert", "Karakum Desert"],
        correctAnswer: "Gobi Desert",
    },
    {
        id: 33,
        question: "Who developed the theory of evolution by natural selection?",
        choices: ["Isaac Newton", "Charles Darwin", "Gregor Mendel", "Alfred Russel Wallace"],
        correctAnswer: "Charles Darwin",
    },
    {
        id: 34,
        question: "What is the capital of Canada?",
        choices: ["Toronto", "Vancouver", "Ottawa", "Montreal"],
        correctAnswer: "Ottawa",
    },
    {
        id: 35,
        question: "Which is the longest river in the world?",
        choices: ["Amazon River", "Nile River", "Yangtze River", "Mississippi River"],
        correctAnswer: "Nile River",
    },
    {
        id: 36,
        question: "What is the currency of Mexico?",
        choices: ["Peso", "Dollar", "Euro", "Real"],
        correctAnswer: "Peso",
    },
    {
        id: 37,
        question: "Who was the first woman to win a Nobel Prize?",
        choices: ["Marie Curie", "Rosalind Franklin", "Dorothy Crowfoot Hodgkin", "Barbara McClintock"],
        correctAnswer: "Marie Curie",
    },
    {
        id: 38,
        question: "In which year did World War I begin?",
        choices: ["1914", "1916", "1918", "1920"],
        correctAnswer: "1914",
    },
    {
        id: 39,
        question: "What is the main ingredient in guacamole?",
        choices: ["Tomato", "Avocado", "Onion", "Cilantro"],
        correctAnswer: "Avocado",
    },
    {
        id: 40,
        question: "Who wrote 'The Great Gatsby'?",
        choices: ["F. Scott Fitzgerald", "Ernest Hemingway", "Jane Austen", "Charles Dickens"],
        correctAnswer: "F. Scott Fitzgerald",
    },
    {
        id: 41,
        question: "Which planet is known as the 'Red Planet'?",
        choices: ["Mars", "Venus", "Jupiter", "Saturn"],
        correctAnswer: "Mars",
    },
    {
        id: 42,
        question: "What is the currency of Russia?",
        choices: ["Ruble", "Peso", "Dinar", "Zloty"],
        correctAnswer: "Ruble",
    },
    {
        id: 43,
        question: "Who is known as the 'Father of Physics'?",
        choices: ["Isaac Newton", "Albert Einstein", "Galileo Galilei", "Niels Bohr"],
        correctAnswer: "Galileo Galilei",
    },
    {
        id: 44,
        question: "Which planet is known as the 'Blue Planet'?",
        choices: ["Mars", "Earth", "Venus", "Jupiter"],
        correctAnswer: "Earth",
    },
    {
        id: 45,
        question: "What is the largest mammal on Earth?",
        choices: ["Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
        correctAnswer: "Blue Whale",
    },
    {
        id: 46,
        question: "Who wrote 'Romeo and Juliet'?",
        choices: ["William Shakespeare", "Jane Austen", "Charles Dickens", "Leo Tolstoy"],
        correctAnswer: "William Shakespeare",
    },
    {
        id: 47,
        question: "Which gas do plants absorb from the atmosphere?",
        choices: ["Carbon Monoxide", "Oxygen", "Nitrogen", "Carbon Dioxide"],
        correctAnswer: "Carbon Dioxide",
    },
    {
        id: 48,
        question: "What is the capital of Australia?",
        choices: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
        correctAnswer: "Canberra",
    },
    {
        id: 49,
        question: "Who invented the telephone?",
        choices: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla", "Galileo Galilei"],
        correctAnswer: "Alexander Graham Bell",
    },
    {
        id: 50,
        question: "Which ocean is the largest?",
        choices: ["Atlantic Ocean", "Indian Ocean", "Southern Ocean", "Pacific Ocean"],
        correctAnswer: "Pacific Ocean"
    }
];